import React,{useEffect,useState} from 'react';
import type {Target} from '../../collector/model';
import {appearance,defaultAppearance,routeKey,Appearance} from '../../collector/preferences';
import './style.css';
import {ServiceLogo} from '../../collector/ServiceLogo';
export interface PopupServices {call:<T=any>(action:string,data?:any)=>Promise<T>;openSettings:()=>void;close:()=>void}
function Icon({name}:{name:string}){return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name==='download'?<><path d="M12 3v12m-4-4 4 4 4-4M4 16v4h16v-4"/></>:name==='eagle'?<><path d="m3 5 9 6 9-6-5 14-4-4-4 4z"/><path d="m12 11 4 8"/></>:name==='feishu'?<><path d="m3 11 18-7-6 17-4-7-8-3Z"/><path d="m11 14 10-10"/></>:name==='arrow'?<path d="m9 5 7 7-7 7"/>:<><rect x="4" y="4" width="16" height="16" rx="4"/><path d="M8 9h8M8 13h5"/></>}</svg>}
function Toggle({label,checked,disabled,onChange}:{label:string;checked:boolean;disabled:boolean;onChange:()=>void}){return <button type="button" className="toggle" role="switch" aria-label={label} aria-checked={checked} disabled={disabled} onClick={onChange}><span/></button>}
export function Popup({services}:{services:PopupServices}){
 const [features,setFeatures]=useState(defaultAppearance),[prefs,setPrefs]=useState<any>({}),[targets,setTargets]=useState<Target[]>([]),[count,setCount]=useState(0),[appId,setAppId]=useState(''),[secret,setSecret]=useState(''),[configured,setConfigured]=useState(false),[editing,setEditing]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(false),[eagle,setEagle]=useState<any>();
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');setError(false);try{await fn();}catch(e){setError(true);setMessage((e as Error).message||'操作失败，请重试');}finally{setBusy(false);}};
 useEffect(()=>{let active=true;Promise.all([services.call('getConfig'),services.call('preferences'),services.call('listPosts')]).then(([c,p,posts])=>{if(!active)return;setAppId(c.appId);setConfigured(c.hasSecret);setTargets(c.targets);setPrefs(p);setFeatures(appearance(p.appearance));setCount(posts.length);}).catch(e=>{if(active){setError(true);setMessage(e.message);}}).finally(()=>{if(active)setBusy(false);});return ()=>{active=false;};},[]);
 const toggle=(key:keyof Appearance)=>run(async()=>{const p=await services.call('savePreferences',{appearance:{[key]:!features[key]}});setFeatures(appearance(p.appearance));setPrefs(p);setMessage('设置已保存');});
 const connect=()=>run(async()=>{const info=await services.call('eagleInfo');setEagle(info);setMessage('已连接 Eagle');});
 const defaultTarget=(id:string)=>run(async()=>{setPrefs(await services.call('savePreferences',{targetId:id}));setMessage('默认表已更新');});
 return <div className="popup-shell"><header className="popup-header"><div className="brand"><img src="/icon/logo.svg" width="38" height="38" alt=""/><div><h1>简采<span>JIANCAI</span></h1><p>把灵感，好好留下。</p></div></div><button className="icon-button" aria-label="关闭弹窗" onClick={services.close}>×</button></header>
 <div className="popup-scroll"><button className="collection" onClick={services.openSettings}><span className="collection-icon"><Icon name="list"/></span><span><strong>我的采集库</strong><small>{count} 条灵感 · Excel 导出与批量管理</small></span><Icon name="arrow"/></button>
 <div className="section-label">采集方式 <span>自定义页面上的快捷入口</span></div>
 <section className="feature-card"><div className="feature-heading"><span className="feature-icon download"><Icon name="download"/></span><div><h2>本地下载</h2><p>原视频与全部图片，一键保存</p></div><Toggle label="显示本地下载入口" checked={features.download} disabled={busy} onChange={()=>toggle('download')}/></div></section>
 <section className="feature-card"><div className="feature-heading"><span className="feature-icon eagle"><ServiceLogo name="eagle"/></span><div><h2>导入 Eagle</h2><p>素材、正文和来源一起收藏</p></div><Toggle label="显示 Eagle 入口" checked={features.eagle} disabled={busy} onChange={()=>toggle('eagle')}/></div>{features.eagle&&<div className="card-body"><div className="connection"><span className={'dot '+(eagle?'online':'')}/><span>{eagle?'已连接 · '+eagle.library:prefs.eagle?'已设置收藏位置':'打开 Eagle，连接你的资源库'}</span><button className="text-button" disabled={busy} onClick={connect}>{eagle?'刷新':'连接'}</button></div>{eagle&&<label className="field-label">保存到文件夹<select aria-label="Eagle 默认文件夹" value={prefs.eagle?.libraryId===eagle.libraryId?prefs.eagle?.folderId||'':''} disabled={busy} onChange={e=>{const folderId=e.target.value;run(async()=>{setPrefs(await services.call('saveEagleFolder',{libraryId:eagle.libraryId,folderId}));setMessage('Eagle 文件夹已保存');});}}><option value="">未分类</option>{eagle.folders.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}</div>}</section>
 <section className="feature-card"><div className="feature-heading"><span className="feature-icon feishu"><ServiceLogo name="feishu"/></span><div><h2>同步飞书</h2><p>整理到自己的多维表格</p></div><Toggle label="显示飞书入口" checked={features.feishu} disabled={busy} onChange={()=>toggle('feishu')}/></div>{features.feishu&&<div className="card-body"><div className="credential"><span><small>飞书应用</small><strong>{configured?appId:'尚未配置'}</strong></span><button className="text-button" disabled={busy} onClick={()=>setEditing(!editing)}>{editing?'收起':configured?'编辑':'设置'}</button></div>{editing&&<div className="credential-form"><label className="field-label">App ID<input value={appId} onChange={e=>setAppId(e.target.value)} autoComplete="off" placeholder="cli_…"/></label><label className="field-label">App Secret<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} placeholder={configured?'留空保持原密钥':'仅保存在此浏览器'}/></label><button className="solid-button" disabled={busy} onClick={()=>run(async()=>{await services.call('saveConfig',{appId:appId.trim(),secret:secret.trim()});setSecret('');setConfigured(true);setEditing(false);setMessage('应用凭证已保存');})}>保存应用凭证</button></div>}
 <a className="help-link" href="https://open.feishu.cn/app" target="_blank" rel="noreferrer">飞书应用与 API 权限 <span>↗</span></a>
 <div className="media-setting"><div><strong>同时保存图片与视频</strong><small>单个文件 ≤ 20 MB，超限保留链接</small></div><Toggle label="上传飞书素材附件" checked={features.uploadMedia} disabled={busy} onChange={()=>toggle('uploadMedia')}/></div>
 <div className="targets-heading">默认多维表格<span>按帖子类型分别保存</span></div>
 {targets.length===0?<div className="empty-target">还没有目标表<br/><small>添加后，即可在作品页一键同步。</small></div>:['xhs:video','xhs:image','dy:video','dy:image','xhs:unconfigured'].map(key=>{const group=targets.filter(t=>routeKey(t)===key);if(!group.length)return null;return <fieldset className="target-group" key={key}><legend>{{'xhs:video':'小红书 · 视频','xhs:image':'小红书 · 图文','dy:video':'抖音 · 视频','dy:image':'抖音 · 图文','xhs:unconfigured':'小红书 · 待指定类型'}[key]}</legend>{group.map(t=><label className="target-option" key={t.id}><input type="radio" name={key} disabled={busy||key.endsWith('unconfigured')} checked={prefs.targets?.[key]===t.id||(key==='dy:video'&&prefs.targets?.dy===t.id)} onChange={()=>defaultTarget(t.id)}/><span><strong>{t.name}</strong><small title={t.base}>my.feishu.cn/base/{t.base.slice(0,9)}…</small></span><a href={`https://my.feishu.cn/base/${t.base}?table=${t.table}`} aria-label={`打开${t.name}`} target="_blank" rel="noreferrer">↗</a></label>)}</fieldset>})}
 <button className="add-target" onClick={services.openSettings}>＋ 添加 / 管理目标表</button><p className="tiny-note">字段映射与自动补列，可在完整设置中调整。</p></div>}</section>
 <section className="feature-card extra-buttons" aria-label="其他页面按钮"><h2>其他页面按钮</h2><p>上方三个开关控制下载、Eagle 和飞书入口。</p><div className="button-setting"><span>更多菜单</span><Toggle label="显示更多菜单" checked={features.more} disabled={busy} onChange={()=>toggle('more')}/></div><small>仅控制作品页按钮显示，已采集的数据和同步配置会保留。</small></section>
 <footer className="popup-footer"><span className="privacy-dot"/> 数据留在你的浏览器，去向由你决定</footer></div>
 {message&&<div className={'feedback '+(error?'error':'')} role={error?'alert':'status'}>{message}</div>}</div>;
}
