import {workbook} from '../../collector/excel';
import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {Post,Platform,Target,schemas,attachmentNames} from '../../collector/model';
import {rpc} from '../../collector/rpc';
import type {Field} from '../../collector/feishu';
import './style.css';

function App(){const [posts,setPosts]=useState<Post[]>([]),[settings,setSettings]=useState(false),[appId,setAppId]=useState(''),[secret,setSecret]=useState(''),[hasSecret,setHasSecret]=useState(false),[targets,setTargets]=useState<Target[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[syncTarget,setSyncTarget]=useState('');
 const [draft,setDraft]=useState<Target>({id:'',name:'',platform:'xhs',base:'',table:'',mapping:{}}),[baseLink,setBaseLink]=useState(''),[tables,setTables]=useState<any[]>([]),[columns,setColumns]=useState<Field[]>([]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('处理中…');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const refresh=async()=>{setPosts(await rpc('listPosts'));const c=await rpc('getConfig');setTargets(c.targets);setAppId(c.appId);setHasSecret(c.hasSecret);};
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));},[]);
 const loadTables=async()=>{let base=baseLink.trim();if(base.startsWith('https://')){const u=new URL(base);if(!/(^|\.)feishu\.cn$/.test(u.hostname))throw new Error('请填写飞书 Base 链接');base=u.pathname.match(/^\/base\/([a-zA-Z0-9]+)/)?.[1]||'';}if(!base)throw new Error('请填写 /base/ 格式的多维表格链接');const list=await rpc<any[]>('tables',base);setTables(list);setColumns([]);setDraft({...draft,base,table:'',mapping:{}});setMessage(`读到 ${list.length} 张数据表，请选择`);};
 const loadFields=async(table:string)=>{const mapping=Object.fromEntries(schemas[draft.platform].map(name=>[name,name]));const t={...draft,name:draft.name.trim()||tables.find(item=>item.table_id===table)?.name||'',table,mapping};const fields=await rpc<Field[]>('ensureFields',t);setColumns(fields);setDraft(t);setMessage('已补齐缺失字段并按同名列匹配；选择“不写入”的字段会保留');};
 const saveTarget=async()=>{const idName=draft.platform==='xhs'?'笔记ID':'视频ID';if(!draft.mapping[idName])throw new Error('作品 ID 必须映射');const used=Object.values(draft.mapping).filter(Boolean);if(new Set(used).size!==used.length)throw new Error('多个来源字段不能映射到同一列');if(!draft.name.trim())throw new Error('请填写目标名称');const saved=await rpc<Target>('saveTarget',draft);setDraft(saved);await refresh();setMessage(`目标表配置已保存：${saved.name}`);};
 const batchSync=async()=>{if(!syncTarget||!selected.length)throw new Error('请选择作品与飞书目标表');const t=targets.find(t=>t.id===syncTarget)!;const rows=posts.filter(p=>selected.includes(p.key));if(rows.some(p=>p.platform!==t.platform))throw new Error('选中的作品必须与目标表属于同一平台');const logs:string[]=[];for(const p of rows){try{const r=await rpc('sync',{key:p.key,targetId:syncTarget});logs.push(`${p.id}：${r.warnings.length?'信息成功，素材提示 '+r.warnings.join('；'):'保存并回读成功'}`);}catch(e){logs.push(`${p.id}：${(e as Error).message}`);}setMessage(logs.join('\n'));}};
 return <main><header><div><small>COMPACT COLLECTOR</small><h1>简采<span>把值得留下的内容，收在一起。</span></h1></div><button onClick={()=>setSettings(!settings)}>{settings?'返回采集列表':'飞书设置'}</button></header>
 <div className="notice" role="status">{message||'单条与主页采集会自动累计在这里。重复作品更新信息。'}</div>
 {settings?<section><h2>飞书应用</h2><p>使用自建应用，将应用添加为目标多维表格的协作者，开通多维表格读写与云空间素材上传权限。凭证仅保存在本机扩展中。</p><div className="row"><label>App ID<input value={appId} onChange={e=>setAppId(e.target.value)}/></label><label>App Secret<input type="password" autoComplete="off" placeholder={hasSecret?'已保存；留空保持不变':''} value={secret} onChange={e=>setSecret(e.target.value)}/></label><button disabled={busy} onClick={()=>run(async()=>{await rpc('saveConfig',{appId:appId.trim(),secret:secret.trim()});setSecret('');setHasSecret(true);setMessage('凭证已保存在本机');})}>保存凭证</button></div>
 <h2>目标表与字段</h2><p>小红书、抖音的图文与视频必须分别配置不同的数据表；主页混合采集会按作品类型选择同一 Base 中唯一对应的目标。</p><p>选择数据表时自动补齐缺失列；后续同步也会补建映射中缺失的列。不会改变已有列的类型。</p><div className="row"><label>编辑已有配置<select value={draft.id} onChange={e=>{const t=targets.find(t=>t.id===e.target.value);setDraft(t||{id:'',name:'',platform:'xhs',base:'',table:'',mapping:{}});setBaseLink(t?.base||'');setTables(t?[{table_id:t.table,name:t.table}]:[]);setColumns([]);if(t)run(async()=>{setColumns(await rpc('fields',t));setMessage('已读取字段');});}}><option value="">新增目标</option>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>作品类型<select value={draft.contentType||(draft.platform==='dy'?'video':'')} onChange={e=>setDraft({...draft,contentType:e.target.value as 'video'|'image'})}><option value="">请选择图文或视频</option><option value="video">{draft.platform==='dy'?'抖音视频':'小红书视频'}</option><option value="image">{draft.platform==='dy'?'抖音图文':'小红书图文'}</option></select></label><label>名称<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>平台<select value={draft.platform} onChange={e=>{const platform=e.target.value as Platform;setDraft({...draft,platform,contentType:platform==='dy'?'video':undefined,mapping:{}});setColumns([]);}}><option value="xhs">小红书</option><option value="dy">抖音</option></select></label></div>
 <div className="row"><label className="grow">多维表格链接<input value={baseLink} onChange={e=>setBaseLink(e.target.value)} placeholder="https://my.feishu.cn/base/…"/></label><button disabled={busy} onClick={()=>run(loadTables)}>读取数据表</button><label>数据表<select value={draft.table} onChange={e=>run(()=>loadFields(e.target.value))}><option value="">选择数据表</option>{tables.map(t=><option key={t.table_id} value={t.table_id}>{t.name}</option>)}</select></label></div>
 {columns.length>0&&<><div className="mapping">{schemas[draft.platform].map(name=><label key={name}>{name}<select value={draft.mapping[name]||''} onChange={e=>setDraft({...draft,mapping:{...draft.mapping,[name]:e.target.value}})}><option value="">不写入</option>{columns.filter(f=>attachmentNames.has(name)?f.type===17:[1,2,3,4,5,15].includes(f.type)).map(f=><option key={f.field_id} value={f.field_name}>{f.field_name}</option>)}</select></label>)}</div><div className="save-target"><button className="primary" disabled={busy} onClick={()=>run(saveTarget)}>{busy?'处理中…':'保存目标与映射'}</button><div className="notice" role="status">{message}</div></div></>}
 <p>素材默认同步。单个文件超过 20 MB 或无法确认大小时，保留链接并提示；已有附件保留；失败后重试会补充缺失素材。</p></section>:<><section className="controls"><strong>{posts.length} 条作品</strong><button disabled={busy} onClick={()=>run(async()=>{await refresh();setMessage('列表已刷新');})}>刷新</button><button disabled={!posts.length||busy} onClick={()=>{XLSX.writeFile(workbook(selected.length?posts.filter(p=>selected.includes(p.key)):posts),`简采-${new Date().toISOString().slice(0,10)}.xlsx`);setMessage('已导出 Excel（选中作品优先；未选则导出全部）');}}>导出 Excel</button><select aria-label="同步目标" value={syncTarget} onChange={e=>setSyncTarget(e.target.value)}><option value="">飞书目标表</option>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button disabled={busy||!selected.length} onClick={()=>run(batchSync)}>同步选中作品</button></section>
 <section className="table"><table><thead><tr><th><input aria-label="全选" type="checkbox" checked={posts.length>0&&selected.length===posts.length} onChange={e=>setSelected(e.target.checked?posts.map(p=>p.key):[])}/></th><th>平台 / 作者</th><th>作品</th><th>赞 / 藏 / 评</th><th>采集时间</th></tr></thead><tbody>{posts.map(p=><tr key={p.key}><td><input aria-label={`选择 ${p.id}`} type="checkbox" checked={selected.includes(p.key)} onChange={e=>setSelected(e.target.checked?[...selected,p.key]:selected.filter(k=>k!==p.key))}/></td><td>{p.platform==='xhs'?'小红书':'抖音'}<small>{p.fields['博主昵称']||p.fields['达人昵称']}</small></td><td><a href={String(p.fields['笔记链接']||p.fields['视频链接'])} target="_blank" rel="noreferrer">{String(p.fields['笔记标题']||p.fields['视频描述']||p.id).slice(0,130)}</a><details><summary>完整内容与字段</summary><pre>{Object.entries(p.fields).map(([k,v])=>`${k}：${Array.isArray(v)?v.join('、'):v}`).join('\n')}</pre></details></td><td>{p.fields['点赞量']??'—'} / {p.fields['收藏量']??'—'} / {p.fields['评论量']??'—'}</td><td>{new Date(Number(p.fields['采集时间'])).toLocaleString()}</td></tr>)}</tbody></table>{!posts.length&&<div className="empty">在小红书或抖音打开作品，点击「＋ 采集」。</div>}</section></>}
 <footer>简采 · 基于 social-media-copilot（GPL-3.0）修改 · 本地自用版</footer></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
